import createElement, { HTMLProperties, SVGElementTagNameMapExtra } from './create-element';

const createSVGElement = createElement as <K extends keyof SVGElementTagNameMap>(tagName: K, ...properties: (HTMLProperties<SVGElementTagNameMapExtra<K>>|(string|Node)[])[]) => SVGElementTagNameMap[K];
const createSVGElementFactory = <K extends keyof SVGElementTagNameMap>(tagName: K) => (...properties: (HTMLProperties<SVGElementTagNameMapExtra<K>>|(string|Node)[])[]) => createSVGElement(tagName, ...properties);

export const a = createSVGElementFactory('a');
export const aTag = a;
export const circle = createSVGElementFactory('circle');
export const clipPath = createSVGElementFactory('clipPath');
export const defs = createSVGElementFactory('defs');
export const desc = createSVGElementFactory('desc');
export const ellipse = createSVGElementFactory('ellipse');
export const feBlend = createSVGElementFactory('feBlend');
export const feColorMatrix = createSVGElementFactory('feColorMatrix');
export const feComponentTransfer = createSVGElementFactory('feComponentTransfer');
export const feComposite = createSVGElementFactory('feComposite');
export const feConvolveMatrix = createSVGElementFactory('feConvolveMatrix');
export const feDiffuseLighting = createSVGElementFactory('feDiffuseLighting');
export const feDisplacementMap = createSVGElementFactory('feDisplacementMap');
export const feDistantLight = createSVGElementFactory('feDistantLight');
export const feFlood = createSVGElementFactory('feFlood');
export const feFuncA = createSVGElementFactory('feFuncA');
export const feFuncB = createSVGElementFactory('feFuncB');
export const feFuncG = createSVGElementFactory('feFuncG');
export const feFuncR = createSVGElementFactory('feFuncR');
export const feGaussianBlur = createSVGElementFactory('feGaussianBlur');
export const feImage = createSVGElementFactory('feImage');
export const feMerge = createSVGElementFactory('feMerge');
export const feMergeNode = createSVGElementFactory('feMergeNode');
export const feMorphology = createSVGElementFactory('feMorphology');
export const feOffset = createSVGElementFactory('feOffset');
export const fePointLight = createSVGElementFactory('fePointLight');
export const feSpecularLighting = createSVGElementFactory('feSpecularLighting');
export const feSpotLight = createSVGElementFactory('feSpotLight');
export const feTile = createSVGElementFactory('feTile');
export const feTurbulence = createSVGElementFactory('feTurbulence');
export const filter = createSVGElementFactory('filter');
export const foreignObject = createSVGElementFactory('foreignObject');
export const g = createSVGElementFactory('g');
export const gTag = g;
export const image = createSVGElementFactory('image');
export const line = createSVGElementFactory('line');
export const linearGradient = createSVGElementFactory('linearGradient');
export const marker = createSVGElementFactory('marker');
export const mask = createSVGElementFactory('mask');
export const metadata = createSVGElementFactory('metadata');
export const path = createSVGElementFactory('path');
export const pattern = createSVGElementFactory('pattern');
export const polygon = createSVGElementFactory('polygon');
export const polyline = createSVGElementFactory('polyline');
export const radialGradient = createSVGElementFactory('radialGradient');
export const rect = createSVGElementFactory('rect');
export const script = createSVGElementFactory('script');
export const stop = createSVGElementFactory('stop');
export const style = createSVGElementFactory('style');
export const svg = createSVGElementFactory('svg');
export const switchTag = createSVGElementFactory('switch');
export const symbol = createSVGElementFactory('symbol');
export const text = createSVGElementFactory('text');
export const textPath = createSVGElementFactory('textPath');
export const title = createSVGElementFactory('title');
export const tspan = createSVGElementFactory('tspan');
export const use = createSVGElementFactory('use');
export const view = createSVGElementFactory('view');

export default createSVGElement;